spring:
  profiles: production

  datasource:
    name: Delivery20Pool
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.193.0.3:1521/delivery
    username: ARMIRENE
    password: 8q85C9aLd@pP3er
    hikari:
      connection-timeout: 30000 # maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 1 # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 50 # maximum pool size
      idle-timeout: 1800000 # maximum idle time for connection
      max-lifetime: 1800000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true # default auto-commit behavior.

  jpa:
    database: default
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: false
    show-sql: false

  cloud:
    gcp:
      firestore:
        enabled: false
      logging:
        enabled: true

  devtools:
    add-properties: false
    restart:
      enabled: false

  mvc:
    converters:
      preferred-json-mapper: gson

cxf:
  path: /soap-adapter/ws
logging:
  level:
    root: INFO
    co:
      ricky-morty:
        cv: INFO
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: INFO

configuration:
  properties:
    time-zone: GMT-5
    fixedrate:
      milliseconds: 1800000

swagger:
  enabled: true
  version: 2.0

redis:
  host: 10.89.109.251

gcs:
  project-id:
    name: app-369418
  bucket:
    name: app-configs-col

microservices:
  armi-orders-manager:
    url: https://armi-orders-manager-dot-armirene-369418.uc.r.appspot.com/
  armi-orders-service:
    url: https://armi-app-api-qa-rakdtiqnya-uc.a.run.app/

---
spring:
  profiles: develop

  datasource:
    name: Delivery20Pool
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.193.0.3:1521/delivery
    username: ARMIRENE2
    password: Tyf+O*Mm5-xl7Ev8Ik3ScEp$
    hikari:
      connection-timeout: 30000 # maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 1 # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 50 # maximum pool size
      idle-timeout: 1800000 # maximum idle time for connection
      max-lifetime: 1800000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true # default auto-commit behavior.

  jpa:
    database: default
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: false
    show-sql: false

  cloud:
    gcp:
      firestore:
        enabled: false
      logging:
        enabled: true

  devtools:
    add-properties: false
    restart:
      enabled: false

  mvc:
    converters:
      preferred-json-mapper: gson

cxf:
  path: /soap-adapter/ws
logging:
  level:
    root: INFO
    co:
      ricky-morty:
        cv: INFO
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: INFO

configuration:
  properties:
    time-zone: GMT-5
    fixedrate:
      milliseconds: 1800000

swagger:
  enabled: true
  version: 2.0

redis:
  host: 10.89.109.251

gcs:
  project-id:
    name: app-369418
  bucket:
    name: app-configs-col-dev

microservices:
  armi-orders-manager:
    url: https://armi-orders-manager-dev-dot-armirene-369418.uc.r.appspot.com/
  armi-orders-service:
    url: https://armi-app-api-qa-rakdtiqnya-uc.a.run.app/

---
spring:
  profiles: local

  datasource:
    name: Delivery20Pool
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.193.0.3:1521/delivery
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 30000 # maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 1 # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 50 # maximum pool size
      idle-timeout: 1800000 # maximum idle time for connection
      max-lifetime: 1800000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true # default auto-commit behavior.

  jpa:
    database: default
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: false
    show-sql: false

  cloud:
    gcp:
      firestore:
        enabled: false
      logging:
        enabled: true

  devtools:
    add-properties: false
    restart:
      enabled: false

  mvc:
    converters:
      preferred-json-mapper: gson

cxf:
  path: /soap-adapter/ws
logging:
  level:
    root: INFO
    co:
      ricky-morty:
        cv: INFO
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: INFO

configuration:
  properties:
    time-zone: GMT-5
    fixedrate:
      milliseconds: 1800000

swagger:
  enabled: true
  version: 2.0

redis:
  host: 10.89.109.251

gcs:
  project-id:
    name: app-369418
  bucket:
    name: app-configs-col-dev

microservices:
  armi-orders-manager:
    url: https://armi-orders-manager-dev-dot-armirene-369418.uc.r.appspot.com/
  armi-orders-service:
    url: https://armi-app-api-qa-rakdtiqnya-uc.a.run.app/

---
spring:
  profiles: sandbox-ricky-morty

  datasource:
    name: Delivery20Pool
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.232.8.3:1521/delivery
    username: soap
    password: Bogotaftd_2020
    hikari:
      connection-timeout: 30000 # maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 1 # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 50 # maximum pool size
      idle-timeout: 1800000 # maximum idle time for connection
      max-lifetime: 1800000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true # default auto-commit behavior.

  jpa:
    database: default
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: false
    show-sql: false

  cloud:
    gcp:
      firestore:
        enabled: false
      logging:
        enabled: true

  devtools:
    add-properties: false
    restart:
      enabled: false

  mvc:
    converters:
      preferred-json-mapper: gson

cxf:
  path: /soap-adapter/ws
logging:
  level:
    root: INFO
    co:
      ricky-morty:
        cv: INFO
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: INFO

configuration:
  properties:
    time-zone: GMT-5
    fixedrate:
      milliseconds: 1800000

swagger:
  enabled: true
  version: 2.0

redis:
  host: 10.89.109.251

gcs:
  project-id:
    name: app-369418
  bucket:
    name: app-configs-col

apis:
  rick-and-morty-api:
    url: https://rickandmortyapi.com/api/